
name: Python application test with Github Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v1
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        make install -f 'Build an NLP in Cloud9 with Python/Makefile'
    - name: Lint with pylint
      run: |
        make lint -f 'Build an NLP in Cloud9 with Python/Makefile'
    - name: Test with pytest
      run: |
        make test -f 'Build an NLP in Cloud9 with Python/Makefile'
    - name: Format code
      run: |
        make format -f 'Build an NLP in Cloud9 with Python/Makefile'
